"""add_cover_image_consultations_bookings

Revision ID: 4e42ce2d10c0
Revises: f41f88ad131b
Create Date: 2026-06-04 20:42:51.586676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e42ce2d10c0'
down_revision: Union[str, None] = 'f41f88ad131b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE articles ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR")
    op.execute("ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500)")
    op.execute("ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS header_button_text VARCHAR(100)")
    op.execute("ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS footer_ready_text VARCHAR(200)")
    op.execute("ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS footer_button_text VARCHAR(100)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'footer_button_text')
    op.drop_column('site_settings', 'footer_ready_text')
    op.drop_column('site_settings', 'header_button_text')
    op.drop_column('site_settings', 'logo_url')
    op.drop_column('articles', 'cover_image_url')
    # ### end Alembic commands ###
