"""add_author_calendar_fields

Revision ID: 69b37198f663
Revises: 4e42ce2d10c0
Create Date: 2026-06-04 22:44:00.291272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b37198f663'
down_revision: Union[str, None] = '4e42ce2d10c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE authors ADD COLUMN IF NOT EXISTS calendar_type VARCHAR")
    op.execute("ALTER TABLE authors ADD COLUMN IF NOT EXISTS booking_link VARCHAR")
    op.execute("ALTER TABLE authors ADD COLUMN IF NOT EXISTS google_calendar_token JSON")
    op.execute("ALTER TABLE authors ADD COLUMN IF NOT EXISTS google_calendar_id VARCHAR")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'google_calendar_id')
    op.drop_column('authors', 'google_calendar_token')
    op.drop_column('authors', 'booking_link')
    op.drop_column('authors', 'calendar_type')
    # ### end Alembic commands ###
